import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: '600',
})
const inter = Inter({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Nonna',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark antialiased">
      <body className={`${poppins.variable} ${inter.variable}`}>
        <main className="relative flex min-h-screen flex-col bg-[url(../public/bg.svg)] bg-center bg-repeat align-middle lg:h-screen">
          {children}
        </main>
      </body>
    </html>
  )
}
